zed_heading_publisher:
  ros__parameters:
    mag_topic: /zed2i/zed_node/imu/mag
    center_x: -0.629279
    center_z: -0.874388
    zero_heading_deg: 39.7
    publish_rate_hz: 20.0
    frame_id: "zed2i_mag"
    invert_yaw: false
    magnetic_field_scale: 1000000.0
    diagnostic_log_interval_sec: 1.0
    raw_x_axis: "y"
    raw_x_sign: -1.0
    raw_z_axis: "x"
    raw_z_sign: 1.0
