uwb_position_publisher:
  ros__parameters:
    uwb_distances_topic: "/uwb/distances"
    uwb_position_topic: "/uwb/position"
    anchor_1_x: 0.0
    anchor_1_y: 0.0
    anchor_2_x: 1.0
    anchor_2_y: 0.0
    anchor_3_x: 0.0
    anchor_3_y: 1.0
    min_anchor_determinant: 1.0e-9
